import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import AddPhotoAlternateOutlinedIcon from "@mui/icons-material/AddPhotoAlternateOutlined";
import CollectionsOutlinedIcon from "@mui/icons-material/CollectionsOutlined";
import PeopleAltOutlinedIcon from "@mui/icons-material/PeopleAltOutlined";
import PersonAddAltOutlinedIcon from "@mui/icons-material/PersonAddAltOutlined";
import ReviewsOutlinedIcon from "@mui/icons-material/ReviewsOutlined";

const BASE_URL = "http://localhost:3000/api";

const links = [
  "/admin/reviews",
  "/admin/reviews/add",
  "/admin/messages",
  "/admin/users",
  "/admin/users/add",
  "/admin/members",
  "/admin/gallery/add",
  "/admin/gallery",
];

const adminLinks = [
  {
    Icon: ReviewsOutlinedIcon,
    name: "Reviews",
    items: [
      {
        Icon: ReviewsOutlinedIcon,
        name: "All Reviews",
        path: "/admin/reviews",
      },
      {
        Icon: AddOutlinedIcon,
        name: "Add Review",
        path: "/admin/reviews/add",
      },
    ],
  },

  {
    Icon: CollectionsOutlinedIcon,
    name: "Gallery",
    items: [
      {
        Icon: CollectionsOutlinedIcon,
        name: "All Gallery",
        path: "/admin/gallery",
      },
      {
        Icon: AddPhotoAlternateOutlinedIcon,
        name: "Add Images",
        path: "/admin/gallery/add",
      },
    ],
  },
  {
    Icon: PeopleAltOutlinedIcon,
    name: "Users",
    items: [
      {
        Icon: PeopleAltOutlinedIcon,
        name: "All Users",
        path: "/admin/users",
      },
      {
        Icon: PersonAddAltOutlinedIcon,
        name: "Add User",
        path: "/admin/users/add",
      },
    ],
  },
];

const messagesTableHeads = ["S.N.", "Name", "Email", "Message", "Sent Date"];
const reviewTableHeads = ["S.N.", "User", "Review", "Created Date", "Actions"];
const userTableHeads = [
  "S.N.",
  "Name",
  "Email",
  "Role",
  "Created Date",
  "Actions",
];
const membersTableHeads = [
  "S.N.",
  "Member Details",
  "Address",
  "Sector",
  "Message",
  "Date",
  "Actions",
];

// Delete Later
const sampleMessages = [
  {
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    message: "Hello, I need help with my order.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    message: "Can you provide more details on the product?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Alice",
    last_name: "Johnson",
    email: "alice.johnson@example.com",
    message: "I have a question about your services.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Bob",
    last_name: "Brown",
    email: "bob.brown@example.com",
    message: "My account is not working. Please assist.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Charlie",
    last_name: "Davis",
    email: "charlie.davis@example.com",
    message: "I would like to cancel my subscription.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Diana",
    last_name: "Miller",
    email: "diana.miller@example.com",
    message: "Can you help me with a refund?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Eve",
    last_name: "Wilson",
    email: "eve.wilson@example.com",
    message: "I am interested in your new product line.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Frank",
    last_name: "Moore",
    email: "frank.moore@example.com",
    message: "Do you offer international shipping?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Grace",
    last_name: "Taylor",
    email: "grace.taylor@example.com",
    message: "How can I update my payment information?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Hank",
    last_name: "Anderson",
    email: "hank.anderson@example.com",
    message: "My order status is not updating.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Ivy",
    last_name: "Thomas",
    email: "ivy.thomas@example.com",
    message: "What are your business hours?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Jack",
    last_name: "Jackson",
    email: "jack.jackson@example.com",
    message: "I need technical support for your software.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Kathy",
    last_name: "White",
    email: "kathy.white@example.com",
    message: "Can you provide a discount for bulk orders?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Liam",
    last_name: "Harris",
    email: "liam.harris@example.com",
    message: "I would like to provide feedback on my recent purchase.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Mona",
    last_name: "Clark",
    email: "mona.clark@example.com",
    message: "Is there a way to track my shipment?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Nina",
    last_name: "Rodriguez",
    email: "nina.rodriguez@example.com",
    message: "I need assistance with an exchange.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Oscar",
    last_name: "Lewis",
    email: "oscar.lewis@example.com",
    message: "Can you help me reset my password?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Paul",
    last_name: "Walker",
    email: "paul.walker@example.com",
    message: "What is your return policy?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Quinn",
    last_name: "Hall",
    email: "quinn.hall@example.com",
    message: "I have not received my confirmation email.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Rita",
    last_name: "Allen",
    email: "rita.allen@example.com",
    message: "Do you offer gift cards?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Sam",
    last_name: "Young",
    email: "sam.young@example.com",
    message: "Can you help with a billing issue?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Tina",
    last_name: "King",
    email: "tina.king@example.com",
    message: "Are your products environmentally friendly?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Ulysses",
    last_name: "Wright",
    email: "ulysses.wright@example.com",
    message: "I would like to speak with a manager.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Vera",
    last_name: "Lopez",
    email: "vera.lopez@example.com",
    message: "Can I update my delivery address?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Will",
    last_name: "Scott",
    email: "will.scott@example.com",
    message: "I have a question about your warranty.",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Xena",
    last_name: "Green",
    email: "xena.green@example.com",
    message: "Is there a loyalty program?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Yves",
    last_name: "Adams",
    email: "yves.adams@example.com",
    message: "How do I unsubscribe from your newsletter?",
    created_at: new Date().toISOString(),
  },
  {
    first_name: "Zara",
    last_name: "Baker",
    email: "zara.baker@example.com",
    message: "Can you provide a product catalog?",
    created_at: new Date().toISOString(),
  },
];

const reviews = [
  {
    id: "e9b8f2a3-5eeb-4f62-bba2-45c8b8a4e3e4",
    name: "Alice Johnson",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Excellent service! The product arrived on time and exceeded my expectations.",
  },
  {
    id: "a45b03f4-0f39-4f3b-8cb1-41e5a9ecdd1c",
    name: "Bob Brown",
    avatar: null,
    created_at: new Date().toISOString(),
    reviews:
      "Good quality but the delivery was delayed. Overall, satisfied with the purchase.",
  },
  {
    id: "c9b4a2d9-5e4f-4e2a-9b3e-8f7e5b89b6e3",
    name: "Charlie Davis",
    avatar: null,
    created_at: new Date().toISOString(),
    reviews:
      "Great product but had some issues with customer service. Could be improved.",
  },
  {
    id: "b1c3e5d8-2e9f-41a3-9f87-4d8e4b4c5a6b",
    name: "Diana Miller",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Love the product! The quality is top-notch and the price was reasonable.",
  },
  {
    id: "f7e5c4a0-2e6f-4b3b-b7d1-9c8e5d9f5a4b",
    name: "Eve Wilson",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "The item was okay, but I was expecting better based on the description.",
  },
  {
    id: "d3b5c6a8-4f2b-5e4d-a5e9-1c9f7e8a6b4d",
    name: "Frank Moore",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Fantastic experience! The customer service was exceptional and very helpful.",
  },
  {
    id: "b2d8e4f9-6e3a-4b4e-8d1c-4b6f9a7e5d8a",
    name: "Grace Taylor",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Product arrived damaged but the return process was easy and efficient.",
  },
  {
    id: "e8c5f6d9-3b7e-4c9f-a1d6-8e9c5b7a6f2b",
    name: "Hank Anderson",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Very satisfied with my purchase. Will definitely shop here again!",
  },
  {
    id: "a6b9c3d8-1e5f-4a3e-b8d1-2e9f6c7a8b4e",
    name: "Ivy Thomas",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "The product did not match the description on the website. Disappointing.",
  },
  {
    id: "c4d8e5f6-3e7b-4d5f-a2e1-9b8c6a7f4e2b",
    name: "Jack Jackson",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    created_at: new Date().toISOString(),
    reviews:
      "Good value for the money. The shipping was fast and the product is as described.",
  },
];

const users = [
  {
    id: "a8b9f2d3-1c5e-4f7b-a6d4-b5c6d7e8f9a0",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: "b1c2d3e4-5f6g-7h8i-9j0k-l1m2n3o4p5q6",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "User",
    created_at: new Date().toISOString(),
  },
  {
    id: "c2d3e4f5-6g7h-8i9j-0k1l-m2n3o4p5q6r7",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Moderator",
    created_at: new Date().toISOString(),
  },
  {
    id: "d3e4f5g6-7h8i-9j0k-1l2m-n3o4p5q6r7s8",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    role: "User",
    created_at: new Date().toISOString(),
  },
  {
    id: "e4f5g6h7-8i9j-0k1l-2m3n-o4p5q6r7s8t9",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    role: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: "f5g6h7i8-9j0k-1l2m-3n4o-p5q6r7s8t9u0",
    name: "Diana Miller",
    email: "diana.miller@example.com",
    role: "Moderator",
    created_at: new Date().toISOString(),
  },
  {
    id: "g6h7i8j9-0k1l-2m3n-4o5p-q6r7s8t9u0v1",
    name: "Eve Wilson",
    email: "eve.wilson@example.com",
    role: "User",
    created_at: new Date().toISOString(),
  },
  {
    id: "h7i8j9k0-1l2m-3n4o-5p6q-r7s8t9u0v1w2",
    name: "Frank Moore",
    email: "frank.moore@example.com",
    role: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    id: "i8j9k0l1-2m3n-4o5p-6q7r-s8t9u0v1w2x3",
    name: "Grace Taylor",
    email: "grace.taylor@example.com",
    role: "Moderator",
    created_at: new Date().toISOString(),
  },
  {
    id: "j9k0l1m2-3n4o-5p6q-7r8s-t9u0v1w2x3y4",
    name: "Hank Anderson",
    email: "hank.anderson@example.com",
    role: "User",
    created_at: new Date().toISOString(),
  },
];

const members = [
  {
    id: "e2eab7d2-4d9c-4a1f-9d3b-bc1c4e1b6a4e",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1-555-123-4567",
    country: "USA",
    state: "California",
    city: "Los Angeles",
    street: "123 Elm Street",
    postal_code: "90001",
    sector: "Technology",
    created_at: new Date().toISOString(),
    message: "Looking forward to the upcoming meeting.",
  },
  {
    id: "b1a8c9d3-2f5e-4a6d-8b3c-8c7d9e0a1b2c",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1-555-234-5678",
    country: "USA",
    state: "New York",
    city: "New York",
    street: "456 Oak Avenue",
    postal_code: "10001",
    sector: "Finance",
    created_at: new Date().toISOString(),
    message: "Please confirm the schedule for the quarterly review.",
  },
  {
    id: "c4b9d8a5-1e7f-4d2b-8a1d-9c0f3b4e5a6d",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "+1-555-345-6789",
    country: "USA",
    state: "Texas",
    city: "Houston",
    street: "789 Pine Road",
    postal_code: "77001",
    sector: "Healthcare",
    created_at: new Date().toISOString(),
    message: "Could you provide the latest report on health trends?",
  },
  {
    id: "d5e8f3a6-2f9b-4d3c-8a2e-1b6c7d8e9f0a",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    phone: "+1-555-456-7890",
    country: "USA",
    state: "Florida",
    city: "Miami",
    street: "321 Maple Lane",
    postal_code: "33101",
    sector: "Retail",
    created_at: new Date().toISOString(),
    message: "Need an update on the latest product launch.",
  },
  {
    id: "e6f7a8b9-3d0e-4e1f-9b2c-8d9e0a1b2c3d",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    phone: "+1-555-567-8901",
    country: "USA",
    state: "Illinois",
    city: "Chicago",
    street: "654 Birch Street",
    postal_code: "60601",
    sector: "Education",
    created_at: new Date().toISOString(),
    message: "Inquire about the upcoming educational seminar.",
  },
  {
    id: "f7a8b9c0-4e1f-2d3c-8a9b-0d1e2f3a4b5c",
    name: "Diana Miller",
    email: "diana.miller@example.com",
    phone: "+1-555-678-9012",
    country: "USA",
    state: "Georgia",
    city: "Atlanta",
    street: "987 Cedar Street",
    postal_code: "30301",
    sector: "Real Estate",
    created_at: new Date().toISOString(),
    message: "Please send me the latest property listings.",
  },
  {
    id: "a8b9c0d1-5e2f-4a3b-8d9c-0e1f2a3b4c5d",
    name: "Eve Wilson",
    email: "eve.wilson@example.com",
    phone: "+1-555-789-0123",
    country: "USA",
    state: "Washington",
    city: "Seattle",
    street: "123 Fir Avenue",
    postal_code: "98101",
    sector: "Travel",
    created_at: new Date().toISOString(),
    message: "Requesting details for the upcoming travel package.",
  },
  {
    id: "b9c0d1e2-6f3g-4a4b-9c0d-1e2f3a4b5c6d",
    name: "Frank Moore",
    email: "frank.moore@example.com",
    phone: "+1-555-890-1234",
    country: "USA",
    state: "Arizona",
    city: "Phoenix",
    street: "456 Willow Lane",
    postal_code: "85001",
    sector: "Automotive",
    created_at: new Date().toISOString(),
    message: "Need information on the latest vehicle models.",
  },
  {
    id: "c0d1e2f3-7g4h-5b6c-9d0e-2f3a4b5c6d7e",
    name: "Grace Taylor",
    email: "grace.taylor@example.com",
    phone: "+1-555-901-2345",
    country: "USA",
    state: "Ohio",
    city: "Columbus",
    street: "789 Spruce Street",
    postal_code: "43201",
    sector: "Entertainment",
    created_at: new Date().toISOString(),
    message: "Interested in the upcoming events and shows.",
  },
  {
    id: "d1e2f3a4-8g5h-6b7c-9d0e-3f4a5b6c7d8e",
    name: "Hank Anderson",
    email: "hank.anderson@example.com",
    phone: "+1-555-012-3456",
    country: "USA",
    state: "Michigan",
    city: "Detroit",
    street: "321 Maple Avenue",
    postal_code: "48201",
    sector: "Finance",
    created_at: new Date().toISOString(),
    message: "Inquiring about financial planning services.",
  },
  {
    id: "e2f3a4b5-9g6h-7c8d-0e1f-4a5b6c7d8e9f",
    name: "Ivy Thomas",
    email: "ivy.thomas@example.com",
    phone: "+1-555-123-4567",
    country: "USA",
    state: "Colorado",
    city: "Denver",
    street: "654 Oak Avenue",
    postal_code: "80201",
    sector: "Healthcare",
    created_at: new Date().toISOString(),
    message: "Requesting information on the latest health trends.",
  },
  {
    id: "f3a4b5c6-0g7h-8d9e-1f2a-3b4c5d6e7f8g",
    name: "Jack Jackson",
    email: "jack.jackson@example.com",
    phone: "+1-555-234-5678",
    country: "USA",
    state: "Nevada",
    city: "Las Vegas",
    street: "987 Elm Street",
    postal_code: "89101",
    sector: "Gaming",
    created_at: new Date().toISOString(),
    message: "Looking for details on upcoming gaming events.",
  },
  {
    id: "g4b5c6d7-1e2f-3a4b-5c6d-7e8f9a0b1c2d",
    name: "Liam Scott",
    email: "liam.scott@example.com",
    phone: "+1-555-345-6789",
    country: "USA",
    state: "North Carolina",
    city: "Charlotte",
    street: "321 Birch Lane",
    postal_code: "28201",
    sector: "Retail",
    created_at: new Date().toISOString(),
    message: "Need an update on the latest promotions and offers.",
  },
];

export {
  BASE_URL,
  adminLinks,
  links,
  members,
  membersTableHeads,
  messagesTableHeads,
  reviewTableHeads,
  reviews,
  sampleMessages,
  userTableHeads,
  users,
};
